# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appointment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ppointment.proto\x12\x0b\x61ppointment\"/\n\x15GetAppointmentRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\x05\"{\n\x13\x41ppointmentResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tid_doctor\x18\x02 \x01(\x05\x12\x12\n\nid_patient\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x10\n\x08symptoms\x18\x05 \x01(\t\x12\x11\n\tdiagnosis\x18\x06 \x01(\t2l\n\x12\x41ppointmentService\x12V\n\x0eGetAppointment\x12\".appointment.GetAppointmentRequest\x1a .appointment.AppointmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'appointment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETAPPOINTMENTREQUEST']._serialized_start=34
  _globals['_GETAPPOINTMENTREQUEST']._serialized_end=81
  _globals['_APPOINTMENTRESPONSE']._serialized_start=83
  _globals['_APPOINTMENTRESPONSE']._serialized_end=206
  _globals['_APPOINTMENTSERVICE']._serialized_start=208
  _globals['_APPOINTMENTSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
