# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appointment.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61ppointment.proto\x12\x0b\x61ppointment\"\x07\n\x05\x45mpty\"/\n\x15GetAppointmentRequest\x12\x16\n\x0e\x61ppointment_id\x18\x01 \x01(\x05\"s\n\x0b\x41ppointment\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tid_doctor\x18\x02 \x01(\x05\x12\x12\n\nid_patient\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x10\n\x08symptoms\x18\x05 \x01(\t\x12\x11\n\tdiagnosis\x18\x06 \x01(\t2\x8e\x03\n\x12\x41ppointmentService\x12N\n\x0eGetAppointment\x12\".appointment.GetAppointmentRequest\x1a\x18.appointment.Appointment\x12G\n\x11\x43reateAppointment\x12\x18.appointment.Appointment\x1a\x18.appointment.Appointment\x12Q\n\x11UpdateAppointment\x12\".appointment.GetAppointmentRequest\x1a\x18.appointment.Appointment\x12K\n\x11\x44\x65leteAppointment\x12\".appointment.GetAppointmentRequest\x1a\x12.appointment.Empty\x12?\n\x0fListAppointment\x12\x12.appointment.Empty\x1a\x18.appointment.Appointmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'appointment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=34
  _globals['_EMPTY']._serialized_end=41
  _globals['_GETAPPOINTMENTREQUEST']._serialized_start=43
  _globals['_GETAPPOINTMENTREQUEST']._serialized_end=90
  _globals['_APPOINTMENT']._serialized_start=92
  _globals['_APPOINTMENT']._serialized_end=207
  _globals['_APPOINTMENTSERVICE']._serialized_start=210
  _globals['_APPOINTMENTSERVICE']._serialized_end=608
# @@protoc_insertion_point(module_scope)
